weights: /mydrive/OceanPlastic/yolo-v5/weights/74Percent/weights/best-74.pt
cfg: ./models/custom_yolov5s.yaml
data: ../data.yaml
hyp: data/hyp.scratch.yaml
epochs: 50
batch_size: 16
img_size:
- 416
- 416
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
log_imgs: 16
workers: 8
project: runs/train
name: only-underwater
exist_ok: false
total_batch_size: 16
world_size: 1
global_rank: -1
save_dir: runs/train/only-underwater2
